// Renders a standalone HTML document into a hidden iframe and opens the
// browser's own Print dialog on it - "Save as PDF" there produces the
// actual PDF, so no client-side PDF library is needed. Shared by any page
// that offers a "Print / Save PDF" button.
export function printHtmlDocument(html: string) {
    const iframe = document.createElement('iframe');
    iframe.style.position = 'fixed';
    iframe.style.right = '0';
    iframe.style.bottom = '0';
    iframe.style.width = '0';
    iframe.style.height = '0';
    iframe.style.border = '0';
    document.body.appendChild(iframe);

    const cleanup = () => {
        setTimeout(() => document.body.removeChild(iframe), 500);
    };

    iframe.onload = () => {
        const win = iframe.contentWindow;
        if (!win) return cleanup();
        win.focus();
        win.print();
        win.addEventListener('afterprint', cleanup, { once: true });
        // Fallback in case afterprint doesn't fire (e.g. dialog cancelled in some browsers).
        setTimeout(cleanup, 60000);
    };
    iframe.srcdoc = html;
}

export function escapeHtml(value: string): string {
    return value
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;');
}

// Shared print-document chrome (brand header + title/subtitle + footer) so
// every printed report/sheet in the app looks like one consistent system.
export function printPageShell(opts: { title: string; subtitle: string; generatedBy: string; bodyHtml: string; landscape?: boolean }) {
    const { title, subtitle, generatedBy, bodyHtml, landscape = true } = opts;
    const generatedAt = new Date().toLocaleString();
    return `<!doctype html>
<html>
<head>
<meta charset="UTF-8" />
<title>${escapeHtml(title)}</title>
<style>
  @page { size: A4 ${landscape ? 'landscape' : 'portrait'}; margin: 16mm 14mm; }
  * { box-sizing: border-box; }
  body { font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; color: #101828; margin: 0; }
  .print-header { display: flex; align-items: center; justify-content: space-between; border-bottom: 2px solid #0a1220; padding-bottom: 10px; margin-bottom: 4px; }
  .print-brand { display: flex; align-items: center; gap: 10px; }
  .print-brand img { height: 32px; }
  .print-brand span { font-size: 16px; font-weight: 800; color: #0a1220; }
  .print-meta { text-align: right; font-size: 11px; color: #667085; }
  h1 { font-size: 18px; margin: 14px 0 2px; color: #0a1220; }
  .print-sub { font-size: 11.5px; color: #667085; margin: 0 0 14px; }
  table { width: 100%; border-collapse: collapse; font-size: 11px; }
  thead { display: table-header-group; }
  tr { page-break-inside: avoid; }
  th, td { border: 1px solid #d7dce5; padding: 5px 8px; text-align: left; }
  th { background: #0a1220; color: #fff; font-weight: 600; text-transform: uppercase; font-size: 9.5px; letter-spacing: 0.03em; }
  tbody tr:nth-child(even) { background: #f7f9fc; }
  .print-footer { margin-top: 10px; font-size: 10px; color: #98a2b3; }
</style>
</head>
<body>
  <div class="print-header">
    <div class="print-brand">
      <img src="/logo.png" alt="" onerror="this.style.display='none'" />
      <span>VIALI Home</span>
    </div>
    <div class="print-meta">
      Generated by ${escapeHtml(generatedBy)}<br />
      ${escapeHtml(generatedAt)}
    </div>
  </div>
  <h1>${escapeHtml(title)}</h1>
  <p class="print-sub">${escapeHtml(subtitle)}</p>
  ${bodyHtml}
  <div class="print-footer">VIALI Home — Laboratory &amp; Chemical Inventory</div>
</body>
</html>`;
}
