type Item={id:string;barcode:string;name:string;hazard:string;category:string;quantity:number;unit:string;location:string;supplier:string;batch:string;expiry:string;remarks:string;updated:string};type Move={id:string;itemId:string;name:string;type:'Received'|'Issued'|'Opening';qty:number;date:string};type DB={items:Item[];moves:Move[]};
const KEY='viali-full-offline-v1',getDB=():DB=>JSON.parse(localStorage.getItem(KEY)||'{"items":[],"moves":[]}'),save=(db:DB)=>localStorage.setItem(KEY,JSON.stringify(db)),q=(s:string)=>document.querySelector<HTMLElement>(s)!,esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const style=document.createElement('style');style.textContent='.feature-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:14px}.feature-grid .card{margin:0;text-align:left;font-size:22px}.feature-grid b,.feature-grid small{display:block}.feature-grid b{font-size:13px;margin-top:8px}.feature-grid small{margin-top:3px}.pill{padding:4px 8px;border-radius:99px;background:#fff0d7;color:#91600b;font-size:10px}';document.head.append(style);
function open(title:string,body:string){const d=document.querySelector<HTMLDialogElement>('#feature-dialog')!;q('#feature').innerHTML=`<div class="title"><h2>${esc(title)}</h2><button id="feature-close" class="link">Close</button></div>${body}`;d.showModal();q('#feature-close').onclick=()=>d.close()}
const rows=(values:string[])=>values.length?values.join(''):'<p class="empty">Nothing to show.</p>';
q('#alerts').onclick=()=>{const db=getDB(),soon=Date.now()+90*86400000;open('Inventory alerts',rows(db.items.filter(i=>i.quantity<=2||(i.expiry&&new Date(i.expiry).getTime()<=soon)).map(i=>`<article class="row"><div><b>${esc(i.name)}</b><small>${i.quantity<=0?'Out of stock':i.quantity<=2?'Low stock':'Expiring'} · ${esc(i.location)}</small></div><span class="pill">${i.quantity} ${esc(i.unit)}</span></article>`)))};
q('#suppliers').onclick=()=>{const db=getDB(),names=[...new Set(db.items.map(i=>i.supplier).filter(Boolean))].sort();open('Suppliers',rows(names.map(n=>`<article class="row"><div><b>${esc(n)}</b><small>${db.items.filter(i=>i.supplier===n).length} supplied items</small></div></article>`)))};
q('#audit').onclick=()=>{const db=getDB();open('Audit log',rows(db.moves.map(m=>`<article class="row"><div><b>${esc(m.type)} · ${esc(m.name)}</b><small>${new Date(m.date).toLocaleString()} · ${m.qty}</small></div></article>`)))};
q('#reports').onclick=()=>{const db=getDB();open('Reports',`<div class="card"><b>Current inventory balance</b><p>${db.items.length} items · ${db.items.reduce((a,i)=>a+i.quantity,0)} total units</p></div><div class="card"><b>Low and out of stock</b><p>${db.items.filter(i=>i.quantity<=2).length} items require attention</p></div><div class="card"><b>Movement history</b><p>${db.moves.length} offline transactions</p></div><button id="report-csv" class="primary full">Download inventory CSV</button>`);q('#report-csv').onclick=()=>{const csv=['Barcode,Item,Category,Hazard,Location,Quantity,Unit',...db.items.map(i=>[i.barcode,i.name,i.category,i.hazard,i.location,i.quantity,i.unit].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='viali-inventory-report.csv';a.click()}};
q('#physical').onclick=()=>{const db=getDB(),term=prompt('Scan/type barcode or enter part of the item name:');if(!term)return;const i=db.items.find(x=>x.barcode.toLowerCase()===term.toLowerCase())||db.items.find(x=>x.name.toLowerCase().includes(term.toLowerCase()));if(!i)return alert('Item not found.');const raw=prompt(`Physical count for ${i.name}\nSystem: ${i.quantity} ${i.unit}\nEnter counted quantity:`);if(raw===null)return;const counted=Number(raw);if(counted<0||Number.isNaN(counted))return alert('Invalid quantity.');const diff=counted-i.quantity;i.quantity=counted;i.updated=new Date().toISOString();if(diff)db.moves.unshift({id:crypto.randomUUID(),itemId:i.id,name:i.name,type:diff>0?'Received':'Issued',qty:Math.abs(diff),date:new Date().toISOString()});localStorage.setItem('viali-last-inventory-check',new Date().toISOString());save(db);location.reload()};
q('#admin').onclick=()=>{const db=getDB();let pin=localStorage.getItem('viali-admin-pin');if(!pin){const made=prompt('Create a 4-digit administrator PIN:');if(!made||!/^\d{4}$/.test(made))return alert('PIN must contain 4 digits.');localStorage.setItem('viali-admin-pin',made);pin=made}if(prompt('Enter administrator PIN:')!==pin)return alert('Incorrect PIN.');const users=JSON.parse(localStorage.getItem('viali-local-users')||'["Offline Administrator"]') as string[];open('Administration',`<div class="card"><b>Reference data</b><p>${new Set(db.items.map(i=>i.category)).size} categories · ${new Set(db.items.map(i=>i.hazard)).size} hazards · ${new Set(db.items.map(i=>i.location)).size} locations</p></div><div class="card"><b>Local users and roles</b><p>${users.map(esc).join(' · ')}</p><button id="add-user" class="secondary full">Add local user</button></div><div class="card"><b>Inventory check</b><p>Last completed: ${localStorage.getItem('viali-last-inventory-check')?new Date(localStorage.getItem('viali-last-inventory-check')!).toLocaleString():'Not completed'}</p></div><button id="change-pin" class="secondary full">Change PIN</button>`);q('#add-user').onclick=()=>{const name=prompt('Full name:');if(name){users.push(name);localStorage.setItem('viali-local-users',JSON.stringify(users));alert('User added.')}};q('#change-pin').onclick=()=>{const next=prompt('New 4-digit PIN:');if(next&&/^\d{4}$/.test(next)){localStorage.setItem('viali-admin-pin',next);alert('PIN changed.')}}};
