type Item={id:string;barcode:string;name:string;hazard:string;location:string;quantity:number;unit:string};
const KEY='viali-full-offline-v1';
const read=():Item[]=>{try{return JSON.parse(localStorage.getItem(KEY)||'{"items":[]}').items||[]}catch{return[]}};
const escapeHtml=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const style=document.createElement('style');style.textContent='#admin{display:none!important}.suggest-wrap{position:relative}.suggest-panel{position:absolute;z-index:60;left:0;right:0;top:calc(100% + 5px);background:#fff;border:1px solid #cbdcdf;border-radius:12px;box-shadow:0 16px 40px #06202c30;max-height:310px;overflow:auto}.suggest-panel:empty{display:none}.suggest-option{display:flex;width:100%;justify-content:space-between;gap:10px;text-align:left;padding:12px;border:0;border-bottom:1px solid #e2ebed;background:#fff;color:#17323c}.suggest-option:last-child{border:0}.suggest-option b,.suggest-option small{display:block}.suggest-option small{margin-top:3px}.suggest-option strong{white-space:nowrap;color:#078f83;font-size:12px}';document.head.append(style);
function attach(input:HTMLInputElement,mode:'inventory'|'manual'){
 const wrap=document.createElement('div'),panel=document.createElement('div');wrap.className='suggest-wrap';panel.className='suggest-panel';input.parentNode!.insertBefore(wrap,input);wrap.append(input,panel);
 const update=()=>{const term=input.value.trim().toLowerCase();if(!term){panel.innerHTML='';return}const found=read().filter(i=>i.name.toLowerCase().includes(term)||i.barcode.toLowerCase().includes(term)||i.location.toLowerCase().includes(term)).slice(0,10);panel.innerHTML=found.map(i=>`<button type="button" class="suggest-option" data-code="${escapeHtml(i.barcode)}"><span><b>${escapeHtml(i.name)}</b><small>${escapeHtml(i.barcode)} · ${escapeHtml(i.location||'No location')}</small></span><strong>${i.quantity} ${escapeHtml(i.unit)}</strong></button>`).join('');panel.querySelectorAll<HTMLButtonElement>('.suggest-option').forEach(button=>button.onclick=()=>{if(mode==='inventory'){input.value=button.querySelector('b')!.textContent||'';input.dispatchEvent(new Event('input',{bubbles:true}))}else{input.value=button.dataset.code||'';document.querySelector<HTMLFormElement>('#manual-form')!.requestSubmit()}panel.innerHTML=''})};
 input.addEventListener('input',update);input.addEventListener('focus',update);document.addEventListener('click',e=>{if(!wrap.contains(e.target as Node))panel.innerHTML=''})
}
attach(document.querySelector<HTMLInputElement>('#search')!,'inventory');attach(document.querySelector<HTMLInputElement>('#manual')!,'manual');
